### ISSUE TITLE
使用VlCPlayerView 时候，页面黑屏

### ISSUE THREAD

**Issue by lhh-sofy** [xuyuanzhou/react-native-yz-vlcplayer#1]
你好，当在ios中使用VlCPlayerView时候，发现视频播放区域是黑屏

**Comment by xuyuanzhou** [comment]
你视频的url是正确的么，具体代码是怎样的

**Comment by lhh-sofy** [comment]
黑屏问题已经解决了，是代码有些问题。能在不旋转屏幕的情况下实现视频全屏么？旋转屏幕的话，效果不是特别理想..

**Comment by xuyuanzhou** [comment]
不旋转屏幕的情况下视屏全屏是指什么意思（指纵向的全屏？）。你想要的效果是什么

**Comment by lhh-sofy** [comment]
不好意思，没有描述清楚，目前的全屏是旋转屏幕，重绘视频播放器的大小；除去视频的旋转，别的元素也旋转了。想实现的功能是只有视频播放器旋转全屏，别的页面元素还是竖屏显示的。 类似于 http://www.cocoachina.com/ios/20170329/18978.html

**Comment by xuyuanzhou** [comment]
目前不能，我这边没办法实现。

**Comment by lhh-sofy** [comment]
哦，不能够直接在ios原生中打开一个新的界面播放全屏么？
