### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by harrischelsea** [xuyuanzhou/react-native-yz-vlcplayer#11]
I have the problem with installation. I follow all steps from readme, but I got this error:

**'MobileVLCKit/MobileVLCKit.h' file not found** in RCTVLCPlayer.m

I downloaded this MobileVLCKit framework: 
**MobileVLCKit-3.0-pre-20180822-0635.tar.xz          22-Aug-2018 06:05    269M**

Anyone has the same problem?

**Comment by xuyuanzhou** [comment]
![1066c185-0498-4d61-83f1-5e2d26ef9bd7](https://user-images.githubusercontent.com/13957655/44516263-315b4c80-a6f7-11e8-84dd-d92974170f0c.png)

**Comment by harrischelsea** [comment]
xuyuanzhou, thank you for the your reply.
I imported MobileVLCKit in vlcKit folder, and my Frameworks folder looks like this.

![screen shot 2018-08-23 at 11 48 07](https://user-images.githubusercontent.com/24303843/44518502-acf2d480-a6ca-11e8-854c-e381c4fc384a.png)

**Comment by harrischelsea** [comment]
Thank you xuyuanzhou, 
your answer helps me., that was my problem.
