### ISSUE TITLE
rtsp STREAM

### ISSUE THREAD

**Issue by harrischelsea** [xuyuanzhou/react-native-yz-vlcplayer#12]
Is posible to stream rtsp live stream?

**Comment by xuyuanzhou** [comment]
Could you provide more detail and describe.

**Comment by harrischelsea** [comment]
I have FOSCAM IP Camera and I want to stream video directly from camera.

For example: https://www.foscam.com/faqs/view.html?id=81

You can see rtsp link.

**Comment by xuyuanzhou** [comment]
I think it's posible to stream rtsp live stream.

**Comment by harrischelsea** [comment]
Thank youe for the reply.
Is this the rigth way to do that? Can I add url directly like this? Because, for me, it is not working.
<VlCPlayerView
        source={{ uri: "rtsp://username:Password:@IP:port/videoMain" }}
/>

**Comment by xuyuanzhou** [comment]
<VlCPlayerView
      url="rtsp://username:Password@IP:port/videoMain"
/>

**Comment by xuyuanzhou** [comment]
<VlCPlayerView
    url={"rtsp://username:Password@IP:port/videoMain"}
/>

**Comment by harrischelsea** [comment]
I allready tried that but not working. 
Thank you for your help.
If you find solution, provide it.

**Comment by harrischelsea** [comment]
No I can not, because it is posible to stream only in local network.
I have another question, how can I play youtube video from link? 
I tried url="yt-link" and it is not working.

**Comment by xuyuanzhou** [comment]
It's possible not support  url="yt-link".

**Comment by harrischelsea** [comment]
xuyuanzhou, thank you very much.
