### ISSUE TITLE
报 RCTVLCPlayer  volume和 volumeDown 错误

### ISSUE THREAD

**Issue by WinnieXi** [xuyuanzhou/react-native-yz-vlcplayer#14]

**Comment by WinnieXi** [comment]
￼

**Comment by WinnieXi** [comment]
￼
![1535537295232](https://user-images.githubusercontent.com/5545894/44781267-83e4af00-abb6-11e8-8408-e4aa77e65560.jpg)

**Comment by xuyuanzhou** [comment]
![image](https://user-images.githubusercontent.com/13957655/44783300-7c280900-abbc-11e8-8b04-ae9f2dcc977f.png)
添加如图所示代码

**Comment by WinnieXi** [comment]
非常感谢。。。。。。问题完美解决，
