### ISSUE TITLE
为什么不能播放rtsp视频？

### ISSUE THREAD

**Issue by tzraeq** [xuyuanzhou/react-native-yz-vlcplayer#2]
你好，vlc是可以支持rtsp和rtmp的，但是您的这个为什么不行呢？

**Comment by xuyuanzhou** [comment]
你的视频源地址是什么，在ios中是可以的"rtsp://184.72.239.149/vod/mp4://BigBuckBunny_175k.mov"

**Comment by xuyuanzhou** [comment]
你用1.0.6版本再尝试下

**Comment by tzraeq** [comment]
大神你好，我第一次没说清楚，我说的是直播视频，我用其他vlc播放器都是可以的，比如“rtmp://live.hkstv.hk.lxdns.com/live/hks”

**Comment by xuyuanzhou** [comment]
这个“rtmp://live.hkstv.hk.lxdns.com/live/hks”
在ios上也能播放

**Comment by xuyuanzhou** [comment]
1.你用的是哪个版本测试的
2.你测试的是android还是iOS
3.你的代码是怎样

**Comment by xuyuanzhou** [comment]
android经测试也是可以播放的

**Comment by tzraeq** [comment]
1.是npm上的版本
2.是android
3.代码的话，按照你给的VlCPlayerView，直接复制过来的。

**Comment by tzraeq** [comment]
我发现不论url设置什么，就算是mp4，都是不播放的，工程很简单，没有特殊的东西。

**Comment by xuyuanzhou** [comment]
你用最新版本1.0.6
这个版本修复了这个问题，url识别的问题，之前把 rtsp:之类开头的识别为本地资源导致的

**Comment by xuyuanzhou** [comment]
你把你设置url的代码发一下

**Comment by tzraeq** [comment]
大神，我换1.0.6试试。
url的代码的话，我是直接在render的return之前，设置了，this.state.url = "http://cdn.goluk.cn/video/t1_2.mp4";
然后player的属性，没动，就是url={this.state.url}

**Comment by tzraeq** [comment]
大神，我现在是任何url都不能播放，项目里没有特殊的地方。我用的是雷电模拟器，难道需要真机调试么？

**Comment by xuyuanzhou** [comment]
1.你现在的表现形式是怎样
2.点击一下画面，开启视屏播放

**Comment by tzraeq** [comment]
1.player部分是黑屏
2.player的部分点击没有任何反应
大神方便用微信或者qq交流么？这里发图好不方便。
