### ISSUE TITLE
XCode 10: Build never completes

### ISSUE THREAD

**Issue by thanhvyit** [xuyuanzhou/react-native-yz-vlcplayer#22]
I downloaded the sample projects and did same all steps on install tutorials. Android works fine for me, but iOS project cannot built. It was running very slow, frozen OS and restarted for a while. Could you please try to reproduce and resolve this issue? My XCode versionL 10.0

Thank you so much!

**Comment by xuyuanzhou** [comment]
set your project  Build Settings --> Build Options --> Debug Information Format to DWARF.

**Comment by xuyuanzhou** [comment]
![image](https://user-images.githubusercontent.com/13957655/48329046-d8f67400-e681-11e8-8719-9f186cae1470.png)
