### ISSUE TITLE
xCode 10: build never completes

### ISSUE THREAD

**Issue by huytran123** [xuyuanzhou/react-native-yz-vlcplayer#23]
I downloaded the sample projects and did same all steps on install tutorials. Android works fine for me, but iOS project cannot built. It was running very slow, frozen OS and restarted for a while. Could you please try to reproduce and resolve this issue? My XCode versionL 10.0

Thank you so much!

**Comment by xuyuanzhou** [comment]
![image](https://user-images.githubusercontent.com/13957655/48329054-e1e74580-e681-11e8-8d3f-ccdb6ac2fe57.png)

**Comment by xuyuanzhou** [comment]
set your project Build Settings --> Build Options --> Debug Information Format to DWARF.
