### ISSUE TITLE
demo中能给一个安卓的apk安装包么？

### ISSUE THREAD

**Issue by lhh-sofy** [xuyuanzhou/react-native-yz-vlcplayer#24]

**Comment by xuyuanzhou** [comment]
提供邮箱给你发一个

**Comment by lhh-sofy** [comment]
> 提供邮箱给你发一个

发我qq邮箱吧。。多谢了。390097651@qq.com

**Comment by xuyuanzhou** [comment]
> > 提供邮箱给你发一个
> 
> 发我qq邮箱吧。。多谢了。[390097651@qq.com](mailto:390097651@qq.com)

已发

**Comment by lhh-sofy** [comment]
> > > 提供邮箱给你发一个
> > 
> > 
> > 发我qq邮箱吧。。多谢了。[390097651@qq.com](mailto:390097651@qq.com)
> 
> 已发

你好，我收到这个了，但是打开第一个视频全屏的时候，发现先是横屏全屏，然后马上就变成竖屏全屏了》
