### ISSUE TITLE
请问使用VlcSimplePlayer组件时候，不能自动播放，的点击暂停按钮！

### ISSUE THREAD

**Issue by dongxiaowu** [xuyuanzhou/react-native-yz-vlcplayer#25]
<VlcSimplePlayer
         isLive={true}
         autoReloadLive={true}
         style={[styles.video]}
         url={"rtsp://192.168.1.254/xxxx.mov"}
         Orientation={Orientation} 
         onStartFullScreen={this.onStartFullScreen}
   />

**Comment by xuyuanzhou** [comment]
autoplay={true}
