### ISSUE TITLE
Build IOS

### ISSUE THREAD

**Issue by IosSos** [xuyuanzhou/react-native-yz-vlcplayer#27]
Hi,
if I try download the packages on site:
nightlies.videolan.org/build/iOS/
after try extract the component in archive, I have a problem, the Mac no extract directory, but make an other archive, I try too with other software for archive, but the results are equal.
I have try open in windows and after send to Mac , but when I try open in Mac open alert archive damaged 
can we help me?
and the libstdc++.6.0.9.tbd is deprecated, how resolve this ?

**Comment by xuyuanzhou** [comment]
(1) you can use  dr.unarchiver

（2）remove   libstdc++.6.0.9.tbd

（3）Your Project   Build Settings --> Build Options --> Debug Information Format   set    DWARF.

**Comment by IosSos** [comment]
i solved with extract archive with command line for the library I used libstdc++.
now I have new problem, can write here? or open new issue?

**Comment by xuyuanzhou** [comment]
android  or  ios

**Comment by IosSos** [comment]
android and ios.
for open wait 15sec

`
import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View} from 'react-native';
import { VLCPlayer, VlCPlayerView, VlcSimplePlayer } from 'react-native-yz-vlcplayer';
import Orientation from 'react-native-orientation';


export default class App extends Component<Props> {
  render() {
    return (

         <VlCPlayerView
           style={{width:'100%',height: '100%'}}
           url={'rtsp://link cam here'}
           Orientation={Orientation.lockToLandscape()}
           autoplay={true}
           videoAspectRatio='16:9'
           setOption={"--no-audio"}
        setOption={"--rtsp-tcp"}
        setOption={"--network-caching=" + 150}
        setOption={"--rtsp-caching=" + 150}
        setOption={"--no-stats"}
        setOption={"--tcp-caching=" + 150}
        setOption={"--realrtsp-caching=" + 150}

           />
    );
  }
}
`

**Comment by xuyuanzhou** [comment]
you  can  use  code like  it.

<VlcSimplePlayer
                autoplay={true}
                url='rtsp://184.72.239.149/vod/mp4://BigBuckBunny_175k.mov'
                initType={2}
                initOptions={[
                    "--no-audio",
                    "--rtsp-tcp",
                    "--network-caching=" + 150,
                    "--rtsp-caching=" + 150,
                    "--no-stats",
                    // setOption("--subsdec-encoding");
                    // setOption("--audio-time-stretch");
                    "--tcp-caching=" + 150,
                    "--realrtsp-caching=" + 150,
                ]}
            />

**Comment by IosSos** [comment]
Yeah! it work! thank you so much! 
i have 3 problems now, if I reload app in debug mode (IOS) the player no reload and in Xcode generate in libvlc_ArtRequest: ->  0x1006686f8 <+0>:  ldr    x0, [x0, #0x58] thread 1: EXC_BAD_ACCESS (code=1, address=0x1a246b90fe9).

and only if I click on display the video open in '16:9'.

and this: 
Warning: option --rtsp-caching no longer exists.
Warning: option --tcp-caching no longer exists.
Warning: option --realrtsp-caching no longer exists.
Warning: option --rtsp-caching no longer exists.
Warning: option --tcp-caching no longer exists.
Warning: option --realrtsp-caching no longer exists.

**Comment by xuyuanzhou** [comment]
1.I have  no  idea  to  solve it. 
2.you can use ：

 fullVideoAspectRatio={"16:9"}
 videoAspectRatio={"16:9"}

3. maybe these option is  remove in this  version.

**Comment by IosSos** [comment]
3. if I remove this option the player wait 15sec before load a video, with this option open immediately.

**Comment by cchamikara** [comment]
@IosSos I have the same Thread 1: EXC_BAD_ACCESS issue when set --rtsp-tcp option, did you find a solution for this ?
