### ISSUE TITLE
Archive Error iOS

### ISSUE THREAD

**Issue by IosSos** [xuyuanzhou/react-native-yz-vlcplayer#28]
if try archive project iOS , I have this error:

Strip /Users/user/Library/Developer/Xcode/DerivedData/player-gmmcnsshbqbynlcwphkqyfqtkkwa/Build/Intermediates.noindex/ArchiveIntermediates/player/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libyoga.a (in target: yoga)
    cd /Users/user/Desktop/player/node_modules/react-native/React
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip -S -T /Users/user/Library/Developer/Xcode/DerivedData/player-gmmcnsshbqbynlcwphkqyfqtkkwa/Build/Intermediates.noindex/ArchiveIntermediates/player/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libyoga.a

fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: can't open temporary file: /tmp/strip.T1DJzz (No such file or directory)
Command Strip failed with a nonzero exit code

can you help me?

**Comment by xuyuanzhou** [comment]
Please  provide more information.  

Your   react-native  version?    

react-native-yz-vlcplayer version?

xcode version?

**Comment by IosSos** [comment]
latest version for all 3 question

**Comment by xuyuanzhou** [comment]
Sorry, I have no idea to solve it. I haven't meet this error.

**Comment by IosSos** [comment]
I make all you steps in guide, but have this error
