### ISSUE TITLE
建议在增加一个硬件加速开关属性

### ISSUE THREAD

**Issue by tzraeq** [xuyuanzhou/react-native-yz-vlcplayer#29]
大神，你好，经过一段时间的使用，我发vlc在android上开启硬件加速的话，会有一些兼容性问题，建议将硬件加速的属性设置暴露给js，比如叫haEnabled。这样方便在各种机型上进行调试。

**Comment by xuyuanzhou** [comment]
OK

**Comment by xuyuanzhou** [comment]
版本   1.1.1-beta3

两个必须一起使用

hwDecoderEnabled    属性0或1

hwDecoderForced     属性0或1

**Comment by xuyuanzhou** [comment]
使用1.1.1-beta4版本，该版本修复android黑屏现象 => this.getSurfaceTexture()为null的现象
