### ISSUE TITLE
改进建议

### ISSUE THREAD

**Issue by tzraeq** [xuyuanzhou/react-native-yz-vlcplayer#3]
- api改进建议
> 1 举例，startFullScreen是一个事件，建议改名为onStartFullScreen
> 2 广告，建议用英文缩写Ad，其他相关的，比如ggUrl改成adUrl，showGG改成showAd
> 3 根据最新的vlc，暴露snapshot（截图）和record（录像）的相关方法，android我已经尝试过了，但是没有ios环境，没有尝试

- bug
> 1 播放rtsp实时视频时，因为取不到视频总长度，所以play/pause按钮的初始状态是不对的

**Comment by xuyuanzhou** [comment]
谢谢你的建议，我会尽快修正。   
截图的话会在下个版本会添加上，录像的话待研究。
