### ISSUE TITLE
QUESTION

### ISSUE THREAD

**Issue by tommasoverola** [xuyuanzhou/react-native-yz-vlcplayer#31]
**With which version of android is this version of the pluin compatible?**

**Comment by xuyuanzhou** [comment]
apply plugin: 'com.android.library'


def _ext = rootProject.ext;

def _reactNativeVersion = _ext.has('reactNative') ? _ext.reactNative : '+';
def _compileSdkVersion = _ext.has('compileSdkVersion') ? _ext.compileSdkVersion : 26;
def _buildToolsVersion = _ext.has('buildToolsVersion') ? _ext.buildToolsVersion : '26.0.3';
def _minSdkVersion = _ext.has('minSdkVersion') ? _ext.minSdkVersion : 16;
def _targetSdkVersion = _ext.has('targetSdkVersion') ? _ext.targetSdkVersion : 26;

android {
    compileSdkVersion _compileSdkVersion
    buildToolsVersion _buildToolsVersion

    defaultConfig {
        minSdkVersion _minSdkVersion
        targetSdkVersion _targetSdkVersion
        versionCode 1
        versionName "1.0"
        ndk {
            //支持的abi    可选 精简的库
            abiFilters 'armeabi-v7a'//,'x86_64','arm64-v8a','x86'
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    provided fileTree(dir: 'libs', include: ['*.jar'])
    provided "com.facebook.react:react-native:${_reactNativeVersion}"
    compile 'com.yyl.vlc:vlc-android-sdk:3.0.13'
    //compile 'de.mrmaffen:vlc-android-sdk:2.0.6'
}

**Comment by tommasoverola** [comment]
At first thanks for your Answer, but i will know why if i launch player on android device, with android 4.4 it work, with android 5.0 wont work, but with android 7 and upper work perfect.
I can not explain that.

I hope that you can explain me why,
Thanks for the attention

**Comment by xuyuanzhou** [comment]
with  android  5.0 is  also  work.
