### ISSUE TITLE
Can't play video via http

### ISSUE THREAD

**Issue by B4UGUYS** [xuyuanzhou/react-native-yz-vlcplayer#32]
Hello there, thanks for awesome library.But currently what am I facing is , I can't play video via http.
Is there any ways to play video via http ?
Thanks.

**Comment by xuyuanzhou** [comment]
please  provide more information：
1.Android  or   ios
2.js  code
3.your  http  url

**Comment by B4UGUYS** [comment]
Sorry for my incomplete info . Actually I am testing on android device.
Here is my js code 
                            <VlcSimplePlayer
                                style={{ width: '100%' }}
                                url={'http://192.168.1.53:3000/posts/media/123456'}
                                autoplay={true}
                                initType={2}
                                hwDecoderEnabled={1}
                                hwDecoderForced={1}
                                initOptions={[
                                    "--no-audio",
                                    "--rtsp-tcp",
                                    "--network-caching=" + 150,
                                    "--rtsp-caching=" + 150,
                                    "--no-stats",
                                    "--tcp-caching=" + 150,
                                    "--realrtsp-caching=" + 150,
                                ]}
                                Orientation={Orientation}
                            />

As you can see, my http url is "http://192.168.1.53:3000/posts/media/123456".

**Comment by xuyuanzhou** [comment]
use    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

**Comment by B4UGUYS** [comment]
still not working

**Comment by B4UGUYS** [comment]
any idea for this bro ?

**Comment by xuyuanzhou** [comment]
url='http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4'

**Comment by xuyuanzhou** [comment]
try  it

**Comment by B4UGUYS** [comment]
Ok . Let me try it.

**Comment by B4UGUYS** [comment]
Surprisingly, it works in that url .

**Comment by B4UGUYS** [comment]
It works now. I forgot to set content-type in response object. Sorry for trouble.
