### ISSUE TITLE
onProgress事件的改进

### ISSUE THREAD

**Issue by tzraeq** [xuyuanzhou/react-native-yz-vlcplayer#33]
在直播的时候，onProgress的当前时间还有时长都是0，但是vlc播放的过程中确实会不断的发出这个事件。这个事件发生的时候hasVideoOut是YES，但是大神你的代码中不抛出这个事件。这样在直播的时候就没有办法可以让我通过事件判断hasVideoOut的状态了。建议把此处判断当前时间和时长的代码去掉，这样从逻辑上是没问题的，虽然数据上有点奇怪。

**Comment by xuyuanzhou** [comment]
你是想要在onProgress事件中也把hasVideoOut这个参数暴露给你的意思么

**Comment by tzraeq** [comment]
不止这样的大神，在直播的情况下，ios中的代码，不会触发这个事件。

**Comment by xuyuanzhou** [comment]
你已经确认了不会触发了么？有没有什么可用的源让我测测看

**Comment by xuyuanzhou** [comment]
确实是这样，直播的时候除了onBuffering会触发外
