### ISSUE TITLE
如何播放file://目录下的视频

### ISSUE THREAD

**Issue by whit15** [xuyuanzhou/react-native-yz-vlcplayer#35]
react-native-camera录制的视频，存放于file://路径下，使用VlcSimplePlayer传入url={"file://****"}无法播放，目前只能上传服务器后再播放。
请作者添加播放file://视频功能，感谢。

**Comment by xuyuanzhou** [comment]
android  or  ios

**Comment by xuyuanzhou** [comment]
你可以尝试以  /开头，而不是file://开头

**Comment by tzraeq** [comment]
ios和android都是以“/“开头，没有任何问题。因为最终都会传递给原生的部分，再传递给C的部分，C的部分访问文件，就是以系统的路径格式，android是linux变种，ios是unix变种，file://这种前缀在vlc里应该是不能用的。

**Comment by whit15** [comment]
@tzraeq 明白了，确认是react-native-camera返回的结果自带了这个file://，移除掉file://后播放正常

**Comment by whit15** [comment]
@xuyuanzhou 确实去掉file://后能够播放了，但是这个file://是react-native-camera生成的，我试过react-native-video是可以不经处理播放的，应该是内部用什么别的方式转化过路径的吧

**Comment by xuyuanzhou** [comment]
@whit15 是的

**Comment by whit15** [comment]
@xuyuanzhou 大佬能不能也内部也处理一下呢，issue我先关掉了，非常感谢。
