### ISSUE TITLE
Issue with native component [Invariant Violation: requireNativeComponent: "RCTVLCPlayer" was not found in the UIManager]

### ISSUE THREAD

**Issue by bavuvanet** [xuyuanzhou/react-native-yz-vlcplayer#4]
Dear xuyuanzhou,

I was build successfully but run error when run on device. Below is the error screen. Please help me. Thanks
![screenshot_1531896507](https://user-images.githubusercontent.com/2013562/42864759-b7c8e8b8-8a91-11e8-9825-d883664d9aa6.png)

**Comment by xuyuanzhou** [comment]
Please make sure you had successful addition.  Could  you show you  configuration？

![image](https://user-images.githubusercontent.com/13957655/42991987-d999c1a2-8c39-11e8-8b21-3dfb77440667.png)

**Comment by xuyuanzhou** [comment]
Please make sure you had successful addition.  Could  you show you  configuration？

![image](https://user-images.githubusercontent.com/13957655/42991987-d999c1a2-8c39-11e8-8b21-3dfb77440667.png)

**Comment by bavuvanet** [comment]
Dear xuyuanzhou,
You said exactly. I modified and it run ok.
Thanks 👍

**Comment by joaodematejr** [comment]
+1

**Comment by joaodematejr** [comment]
same problem only on iphone
