### ISSUE TITLE
iOS 编译报错: duplicate symbol

### ISSUE THREAD

**Issue by DongWei02** [xuyuanzhou/react-native-yz-vlcplayer#49]
项目中导入了amap3d和yz-vlcplayer,编译时出现
`duplicate symbol _png_check_chunk_length in:
    Pods/AMap3DMap/MAMapKit.framework/MAMapKit(MAMapKit-x86_64-master.o)
    VLCKit/MobileVLCKit.framework/MobileVLCKit(pngrutil.o)
`
请问要怎么处理这个问题呢

**Comment by tzraeq** [comment]
哪个开源能拿到源码，就该哪个，需要把重复的变量名改掉。好在只有一个。

**Comment by dolphinDW** [comment]
谢谢，已经解决了

**Comment by DongWei02** [comment]
> 哪个开源能拿到源码，就该哪个，需要把重复的变量名改掉。好在只有一个。

谢谢,已经解决了
