### ISSUE TITLE
支持react-native 0.44.3吗？引入link后报support v4错误

### ISSUE THREAD

**Issue by EwanBerg** [xuyuanzhou/react-native-yz-vlcplayer#6]
file:/Users/sierra/Library/Android/sdk/extras/android/m2repository/com/android/support/support-v4/26.1.0/support-v4-26.1.0.pom
               file:/Users/sierra/Library/Android/sdk/extras/android/m2repository/com/android/support/support-v4/26.1.0/support-v4-26.1.0.jar
               file:/Users/sierra/Desktop/new/cwpapp_native/android/sdk-manager/com/android/support/support-v4/26.1.0/support-v4-26.1.0.jar
           Required by:
               cwp_app_native:react-native-yz-vlcplayer:unspecified > com.facebook.react:react-native:0.44.3 > com.android.support:appcompat-v7:23.0.1
请问该如何解决？？？

**Comment by xuyuanzhou** [comment]
你 把   react-native-yz-vlcplayer： build.gradle  里的 sdk编译版本改成你自己的版本
