### ISSUE TITLE
setup error on ios

### ISSUE THREAD

**Issue by hungdev** [xuyuanzhou/react-native-yz-vlcplayer#7]
Thank your library.
But i cant set up on ios.
<img width="905" alt="screen shot 2018-08-11 at 4 33 35 pm" src="https://user-images.githubusercontent.com/12009276/43990661-63c6a0ca-9d88-11e8-9baa-e11b9779882d.png">

i download at here:
http://nightlies.videolan.org/build/iOS/MobileVLCKit-3.0-pre-20180811-0634.tar.xz
(11-Aug-2018 06:05    269M)
step 2: my vlcKit folder:
<img width="827" alt="screen shot 2018-08-11 at 4 37 18 pm" src="https://user-images.githubusercontent.com/12009276/43990323-e462dd60-9d84-11e8-9c84-63fdc1059d55.png">
<img width="844" alt="screen shot 2018-08-11 at 4 38 06 pm" src="https://user-images.githubusercontent.com/12009276/43990326-f587de2e-9d84-11e8-9c25-1eb07d4f569d.png">
step 3:
<img width="282" alt="screen shot 2018-08-11 at 4 39 52 pm" src="https://user-images.githubusercontent.com/12009276/43990343-3467fe12-9d85-11e8-9f1b-83393b7d66b8.png">
step 4: like your guide.
step 5: I do not see it like yours. please look at the picture on step 3

please review my setup. where is my wrong step?

**Comment by hungdev** [comment]
@xuyuanzhou and @bavuvanet could you help me?

**Comment by xuyuanzhou** [comment]
please  ensure  step 4 is  right.

**Comment by hungdev** [comment]
@xuyuanzhou  yes, im sure step 4 is right. But i look at the picture in step 3, its difference with your picture.

**Comment by hungdev** [comment]
@xuyuanzhou could you up example folder to the repository?

**Comment by xuyuanzhou** [comment]
![image](https://user-images.githubusercontent.com/13957655/43993507-35214b4c-9dc1-11e8-9389-4e925ca84f16.png)

**Comment by hungdev** [comment]
this is my step 4.
<img width="1396" alt="screen shot 2018-08-11 at 10 51 49 pm" src="https://user-images.githubusercontent.com/12009276/43993533-2bf620c2-9db9-11e8-8dcf-d60566eeddad.png">

**Comment by xuyuanzhou** [comment]
ok, i will create  example folder as soon as possible.

**Comment by xuyuanzhou** [comment]
Could you clean the project and try it again?  I  do the step like you. I have not  this error like you.

**Comment by hungdev** [comment]
Oke, wait me try again. If it gets the error, i will record a video for you.

**Comment by xuyuanzhou** [comment]
step 5 :   add framework like this.
![image](https://user-images.githubusercontent.com/13957655/43993710-8406fc72-9dc4-11e8-87db-e9f0d40ef58e.png)

**Comment by hungdev** [comment]
@xuyuanzhou in this link http://nightlies.videolan.org/build/iOS/MobileVLCKit-3.0-pre-20180811-0634.tar.xz
when i extract this file,I do not see it like that.
<img width="691" alt="screen shot 2018-08-11 at 11 16 05 pm" src="https://user-images.githubusercontent.com/12009276/43993747-8f71e5b6-9dbc-11e8-8028-59e0e1b1bbb4.png">

**Comment by hungdev** [comment]
This is where I downloaded it
<img width="1535" alt="screen shot 2018-08-11 at 11 17 49 pm" src="https://user-images.githubusercontent.com/12009276/43993775-031a1326-9dbd-11e8-9470-5fbe605c3677.png">

**Comment by xuyuanzhou** [comment]
Could you  see   MobileVLCKit.framework.

**Comment by hungdev** [comment]
@xuyuanzhou where is the files. My MobileVLCKit.framework not like this.
![5](https://user-images.githubusercontent.com/12009276/43993969-5b5b9fa8-9dbf-11e8-8e7c-43826e652ad5.jpeg)

**Comment by xuyuanzhou** [comment]
Other are  ios framework, you can  add that like this:
![image](https://user-images.githubusercontent.com/13957655/43993987-fdec0188-9dc7-11e8-94a0-912d04ce9a06.png)
![image](https://user-images.githubusercontent.com/13957655/43993992-15e6d006-9dc8-11e8-9a97-8aa2a60444d1.png)

**Comment by hungdev** [comment]
add all file .tbd to the frameworks like this?
<img width="349" alt="screen shot 2018-08-11 at 11 44 08 pm" src="https://user-images.githubusercontent.com/12009276/43994037-7bb86ece-9dc0-11e8-8394-6be6a4d5aeb8.png">

And in step 6, i did not find libRCTVLCPlayer.a ?
<img width="475" alt="screen shot 2018-08-11 at 11 43 47 pm" src="https://user-images.githubusercontent.com/12009276/43994039-866229a0-9dc0-11e8-89a2-e860cb16d77b.png">

**Comment by xuyuanzhou** [comment]
You can  clone  this  example.     https://github.com/xuyuanzhou/vlcplayerExample

**Comment by xuyuanzhou** [comment]
If you  did  not  find.  It may be already add.

**Comment by xuyuanzhou** [comment]
You  can  check  here. 
![image](https://user-images.githubusercontent.com/13957655/43994059-5a134362-9dc9-11e8-8577-e5937d9ad8d4.png)

**Comment by hungdev** [comment]
@xuyuanzhou please check my video: https://youtu.be/IID_BAFVbbc

**Comment by xuyuanzhou** [comment]
I found  you  error. The  vlcKit  path is not  in  ios path.
![image](https://user-images.githubusercontent.com/13957655/43994133-6a2f3782-9dca-11e8-8705-abae717de446.png)

**Comment by xuyuanzhou** [comment]
Just add those frameworks  and  librarys     like  the  photo.  
![image](https://user-images.githubusercontent.com/13957655/43994182-389ddc86-9dcb-11e8-8bf0-b4dab829e9c6.png)

**Comment by hungdev** [comment]
Im trying again.

**Comment by hungdev** [comment]
It does not have libRCTVLCPlayer.a file.
<img width="1159" alt="screen shot 2018-08-12 at 12 14 43 am" src="https://user-images.githubusercontent.com/12009276/43994286-c270e428-9dc4-11e8-9ec4-113ed92b06f3.png">

<img width="1137" alt="screen shot 2018-08-12 at 12 15 51 am" src="https://user-images.githubusercontent.com/12009276/43994290-e9050cea-9dc4-11e8-94fd-d571bcaaad25.png">

**Comment by xuyuanzhou** [comment]
Please do these:
1.  run       npm  install  --save  react-native-yz-vlcplayer
2. run       react-native  link  react-native-yz-vlcplayer

**Comment by hungdev** [comment]
Oh my god. I love you so much. I have built successfully. But it got an error. this error due to vector icon. I think i can fix this error.
But you should update docs require user install and run link vector icon.
I look around, I see a lot of lib like your library. But they are all too old and do not support the current native native version. Thank your lib. thank for your support.
I hope you always update this lib until react native stable version. and please update the document to english version.
I would like to thank you again.
<img width="392" alt="screen shot 2018-08-12 at 12 46 54 am" src="https://user-images.githubusercontent.com/12009276/43994564-3ef2b4be-9dc9-11e8-8d39-07f4961ea1c5.png">

**Comment by xuyuanzhou** [comment]
OK, I will do it  as soon as possible.

**Comment by EwanBerg** [comment]
I have the same problem just as you ! But I figured it out   by adding the vlckit to the folder where the ios original sdk 11.4 be .but it is not perfect. When I run my project on my simulator ,the problem remains.But on  my ITouch ,it works fine . I have decided to ask help from yuanzhou ,you came first ! LOL ! I made the same mistake as you did. Added the vlcKit to the wrong path ! Just now , I solved it  by following the way yuanzhou told you .  Best RN rtsp player ! Thank you  too !
