### ISSUE TITLE
Component 'RCTVideo' re-registered bubbling event 'topVideoLoadStart' as a direct event

### ISSUE THREAD

**Issue by A-ANing** [xuyuanzhou/react-native-yz-vlcplayer#73]
Component 'RCTVideo' re-registered bubbling event 'topVideoLoadStart' as a direct event

组件“RCTVideo”已注册冒泡事件“topVideoLoadStart”作为直接事件

Hello, there is no problem with Xcode compilation. What's the matter once it runs

您好，xcode编译没出问题，一运行就这样是怎么回事呀

**Comment by A-ANing** [comment]
已经解决了，我移除了 ‘react-native-video’和‘react-native-video-contros’

It has been solved. I removed "react native video" and "react native video contros"

**Comment by wulaizi** [comment]
不能够和react native video 一起使用吗？
